name: post-deploy checks
on : 
  workflow_dispatch:


jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: checkout code 
       uses: actions/checkout@v4


     - name: checking
       run: | 
        check=$(curl -s -o response.txt -w "%{response_code}" https://tm-thread.com)
        if [ "${check}" != 200 ]; then 
           echo "health check failed"
           exit 1
        else
           echo "health check passed"
        fi
        