name: terraform 
on : 
  pull_request:
    branches: [ main ]
    paths:
      -"infra/**"

  


permissions:
  id-token: write   
  contents: read 
jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: checkout code 
       uses: actions/checkout@v2


     - name: Aws credentials
       uses: aws-actions/configure-aws-credentials@v6
       with:
         role-to-assume: ${{ secrets.TERRAFORM }}
         aws-region: "eu-west-2"
      
     -  name: terraform 
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.14.6"
         terraform_wrapper: false

     - name: terraform init
       run: terrafom init
      
     - name: terraform validate
       run: terraform validate -no-color

     - name: terraform plan
       id: plan
       run: terraform plan -no-color -out=tfplan

     
     - name: upload plan artifect
       uses: actions/upload-artifact@v4
       with:
         name: terraform-plan 
         path: infra/tfplan
         retention-days: 5

     
           