name: terraform 
on : push



permissions:
  id-token: write   
  contents: read 
jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: checkout code 
       uses: actions/checkout@v2

     - name: Aws credentials
       uses: aws-actions/configure-aws-credentials@v6
       with:
         role-to-assume: ${{ secrets.TERRAFORM }}
         aws-region: "eu-west-2"
      
     -  name: terraform 
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.14.6"
     

     - name: terraform init 
       run : |
        cd infra
        terraform init
     - name: tarraform plan 
       run: | 
        cd infra
        terraform plan 